#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         NCustom
version:      0.07
version_from: lib/NCustom.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
